### ISSUE TITLE
Deleted, cut, and moved tables leave artifacts

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#2822]
## Describe the bug
Whenever a table is deleted, cut, or moved it leaves an artifact behind, see GIF. 

## Reproduction

![Image](https://github.com/user-attachments/assets/ba76afbc-b8ae-4ae0-9540-335eb284d19c)

**Comment by AyushAgrawal-A2** [comment]
should be fixed in https://github.com/quadratichq/quadratic/pull/2791

**Comment by luke-quadratic** [comment]
Re-opening, still exists on table borders

https://github.com/user-attachments/assets/ca1c24e3-40c1-408a-9825-9f1df685dc9e
